trigger:
  - none
schedules:
  - cron: "*/5 * * * *"  # Run at 6 AM UTC on the 2nd Wednesday of each month
    displayName: "Monthly Run: 2nd Wednesday - ping.yml"
    branches:
      include:
        - main
        - automation
    always: true
    parameters:
      playbook: 'playbooks/ping.yml'
    
parameters:
- name: playbook
  displayName: 'Select the Playbook name you want to run:'
  type: string
  default: 'test_run2'
  values:
    - 'playbooks/ping.yml'
    - 'test_run2'
    - 'test_run3'
    - 'test_run4'

jobs:
- job: ansible_ping
  displayName: Execute Ansible playbooks
  pool: 
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      sudo apt update
      sudo apt install -y python3-pip
      pip3 install ansible 
    displayName: 'Install Ansible'



  # - task: AzureCLI@2
  #   displayName: Run Ansible playbook
  #   condition: |
  #     or(
  #       eq('${{ parameters.playbook }}', 'playbooks/ping.yml'),
  #       eq('${{ parameters.playbook }}', 'test_run2')
  #     )
  #   inputs:
  #     azureSubscription: 'image2'
  #     scriptType: 'bash'
  #     scriptLocation: 'inlineScript'
  #     inlineScript: |
  #       ansible-inventory -v -i "localhost," --connection=local --graph
  #       ansible-playbook -i "localhost," --connection=local ${{parameters.playbook}} -v

  - task: Ansible@0
    displayName: Run Ansible playbook
    condition: |
      or(
        eq('${{ parameters.playbook }}', 'playbooks/ping.yml'),
        eq('${{ parameters.playbook }}', 'test_run2')
      )
    inputs:
      ansibleInterface: 'agentMachine'
      playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/${{ parameters.playbook }}'
      inventoriesAgentMachine: 'file'
      inventoryFileOnAgentMachine: '$(System.DefaultWorkingDirectory)/host.yml'
      args: '-v'
