trigger:
  - none
parameters:
- name: playbook
  displayName: 'Select the Playbook name you want to run:'
  type: string
  default: 'test_run1'
  values:
    - 'test_run1'
    - 'test_run2'
    - 'test_run3'
    - 'test_run4'

jobs:
- job: ansible_ping
  displayName: Execute Ansible playbooks
  pool: 
    vmImage: 'ubuntu-latest'
  steps:



  - task: AzureCLI@2
    displayName: Run Ansible playbook
    condition: |
      or(
        eq('${{ parameters.playbook }}', 'test_run1'),
        eq('${{ parameters.playbook }}', 'test_run2')
      )
    inputs:
      azureSubscription: 'image2'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        ansible-inventory -v -i "localhost," --connection=local --graph
        ansible-playbook -i "localhost," --connection=local ${{parameters.playbook}} -v

