- name: Ping hosts to check connectivity
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ping the Windows host
      ansible.builtin.ping:
